"""
backend/agents/graph.py
─────────────────────────────────────────────────────
LangGraph state machine for the 5-agent pipeline.

Edge order (sequential):
  supervisor → data_quality → log_analysis → rca
              → recommendation → compliance → aggregator → END

Aggregator: deterministic Python, no LLM.
Assembles incident_report markdown from all five agent findings.
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict

from langgraph.graph import END, StateGraph  # type: ignore

from backend.agents.state import AgentState
from backend.agents.supervisor import supervisor_node
from backend.agents.data_quality_agent import data_quality_node
from backend.agents.log_analysis_agent import log_analysis_node
from backend.agents.rca_agent import rca_node
from backend.agents.recommendation_agent import recommendation_node
from backend.agents.compliance_agent import compliance_node

logger = logging.getLogger(__name__)


# ─── Aggregator (deterministic — no LLM) ────────────────────────────────────

def aggregator_node(state: AgentState) -> AgentState:
    """
    Assembles incident_report_draft.md from all five agent findings.
    Writes file to output_dir.
    Sets status to pending_review (caller handles final persistence).
    """
    run_id = state["run_id"]
    output_dir = state["output_dir"]
    metrics = state.get("sanitized_metrics", {})
    now = datetime.now(timezone.utc).isoformat()

    logger.info(f"[aggregator] Assembling incident report | run_id={run_id}")

    report = _build_report(
        run_id=run_id,
        metrics=metrics,
        dq=state.get("data_quality_findings", ""),
        log_a=state.get("log_analysis_findings", ""),
        rca=state.get("rca_findings", ""),
        rec=state.get("recommendations", ""),
        comp=state.get("compliance_review", ""),
        generated_at=now,
    )

    # Write incident_report_draft.md
    draft_path = os.path.join(output_dir, "incident_report_draft.md")
    os.makedirs(output_dir, exist_ok=True)
    with open(draft_path, "w", encoding="utf-8") as fh:
        fh.write(report)

    logger.info(f"[aggregator] incident_report_draft.md written to {draft_path}")

    return {**state, "incident_report": report}


def _build_report(
    run_id: str,
    metrics: Dict[str, Any],
    dq: str,
    log_a: str,
    rca: str,
    rec: str,
    comp: str,
    generated_at: str,
) -> str:
    health_score = metrics.get("health_score", 0)
    health_label = metrics.get("health_label", "Unknown")
    total_rows = metrics.get("total_rows", 0)
    anomaly_count = metrics.get("anomaly_count", 0)

    # Load confidence scores if available
    conf_note = ""

    return f"""# Clinical Trial AI Observability — Incident Report Draft

**Run ID:** `{run_id}`  
**Generated At:** {generated_at}  
**Status:** Pending Human Review  
**Health Score:** {health_score}/100 ({health_label})  
**Total Records Processed:** {total_rows}  
**Total Anomalies Detected:** {anomaly_count}  

---

## ⚠️ Important
This is an AI-generated draft. A Clinical Data Manager must review and approve
before this report is considered final and binding.

---

## 1. Data Quality Assessment

{dq}

---

## 2. Log Analysis

{log_a}

---

## 3. Root Cause Analysis

{rca}

---

## 4. Recommendations

{rec}

---

## 5. Compliance Review

{comp}

---

## 6. Pipeline Summary

| Metric | Value |
|--------|-------|
| Run ID | `{run_id}` |
| Health Score | {health_score}/100 |
| Health Label | {health_label} |
| Total Rows | {total_rows} |
| Anomaly Count | {anomaly_count} |
| Generated At | {generated_at} |

---

*This report was generated by the Agentic AI Data Observability System v6.0.*  
*All data has been PII/PHI masked using Microsoft Presidio before reaching this report.*  
*Approved reports are stored locally — no cloud storage is used.*
"""


# ─── Graph builder ────────────────────────────────────────────────────────────

def build_graph() -> StateGraph:
    sg = StateGraph(AgentState)

    # Register nodes
    sg.add_node("supervisor", supervisor_node)
    sg.add_node("data_quality", data_quality_node)
    sg.add_node("log_analysis", log_analysis_node)
    sg.add_node("rca", rca_node)
    sg.add_node("recommendation", recommendation_node)
    sg.add_node("compliance", compliance_node)
    sg.add_node("aggregator", aggregator_node)

    # Sequential edges
    sg.set_entry_point("supervisor")
    sg.add_edge("supervisor", "data_quality")
    sg.add_edge("data_quality", "log_analysis")
    sg.add_edge("log_analysis", "rca")
    sg.add_edge("rca", "recommendation")
    sg.add_edge("recommendation", "compliance")
    sg.add_edge("compliance", "aggregator")
    sg.add_edge("aggregator", END)

    return sg.compile()


# Module-level compiled graph
graph = build_graph()


# ─── Pipeline runner ─────────────────────────────────────────────────────────

def run_agent_pipeline(
    run_id: str,
    sanitized_metrics: Dict[str, Any],
    sanitized_log_text: str,
    streaming_metadata: Dict[str, Any],
    output_dir: str,
) -> AgentState:
    """
    Invoke the compiled LangGraph.
    Returns the final AgentState.
    """
    logger.info(f"[graph] Starting agent pipeline | run_id={run_id}")

    initial_state: AgentState = {
        "run_id": run_id,
        "sanitized_metrics": sanitized_metrics,
        "sanitized_log_text": sanitized_log_text,
        "streaming_metadata": streaming_metadata,
        "output_dir": output_dir,
        "data_quality_findings": "",
        "log_analysis_findings": "",
        "rca_findings": "",
        "recommendations": "",
        "compliance_review": "",
        "incident_report": "",
        "audit_entries": [],
        "error": None,
    }

    try:
        final_state = graph.invoke(initial_state)
        logger.info(f"[graph] Agent pipeline complete | run_id={run_id}")
        return final_state
    except Exception as exc:
        logger.error(f"[graph] Agent pipeline failed | run_id={run_id} | error={exc}")
        return {**initial_state, "error": str(exc)}
