"""
graph.py
LangGraph StateGraph definition.
Orchestrates all 5 agents in sequence:
  supervisor → data_quality → log_analysis → rca → recommendation → compliance → aggregator
"""

import json
from datetime import datetime, timezone

from langgraph.graph import StateGraph, END

from backend.agents.state import AgentState
from backend.agents.supervisor import supervisor_node
from backend.agents.data_quality_agent import data_quality_node
from backend.agents.log_analysis_agent import log_analysis_node
from backend.agents.rca_agent import rca_node
from backend.agents.recommendation_agent import recommendation_node
from backend.agents.compliance_agent import compliance_node


# ─────────────────────────────────────────────────────────────────────────────
# Aggregator node — deterministic report assembly, no LLM call
# ─────────────────────────────────────────────────────────────────────────────

def aggregator_node(state: AgentState) -> AgentState:
    """
    Merges all agent outputs into a single formatted markdown incident report.
    No LLM call — pure deterministic assembly.
    """
    now = datetime.now(timezone.utc).isoformat()
    run_id = state.get("run_id", "unknown")

    report = f"""# Clinical Trial Data Pipeline — Incident Report

**Run ID:** `{run_id}`
**Generated:** {now}
**Status:** AI-Generated Draft — Pending Human Review

> This report was generated by an Agentic AI Observability System.
> It requires review and approval by a qualified Clinical Data Manager
> before use in any regulatory submission.

---

## 1. Data Quality Assessment

{state.get('data_quality_findings', '_Not available_')}

---

## 2. Operational Log Analysis

{state.get('log_analysis_findings', '_Not available_')}

---

## 3. Root Cause Analysis

{state.get('rca_findings', '_Not available_')}

---

## 4. Remediation Recommendations

{state.get('recommendations', '_Not available_')}

---

## 5. Compliance Review

{state.get('compliance_review', '_Not available_')}

---

*Report generated by Agentic AI Data Observability System v1.0*
*All agent decisions are logged in the accompanying audit_trail.json file.*
"""

    state["incident_report"] = report
    return state


# ─────────────────────────────────────────────────────────────────────────────
# Graph construction
# ─────────────────────────────────────────────────────────────────────────────

def build_graph():
    """Build and compile the LangGraph StateGraph."""
    workflow = StateGraph(AgentState)

    # Register nodes
    workflow.add_node("supervisor", supervisor_node)
    workflow.add_node("data_quality", data_quality_node)
    workflow.add_node("log_analysis", log_analysis_node)
    workflow.add_node("rca", rca_node)
    workflow.add_node("recommendation", recommendation_node)
    workflow.add_node("compliance", compliance_node)
    workflow.add_node("aggregator", aggregator_node)

    # Define edges (sequential flow)
    # supervisor fans out to both analysis agents
    workflow.set_entry_point("supervisor")
    workflow.add_edge("supervisor", "data_quality")
    workflow.add_edge("data_quality", "log_analysis")
    workflow.add_edge("log_analysis", "rca")
    workflow.add_edge("rca", "recommendation")
    workflow.add_edge("recommendation", "compliance")
    workflow.add_edge("compliance", "aggregator")
    workflow.add_edge("aggregator", END)

    return workflow.compile()


# Compile graph once at module load
graph = build_graph()


def run_agent_pipeline(
    run_id: str,
    sanitized_metrics: dict,
    sanitized_log_text: str,
) -> AgentState:
    """
    Entry point called by the FastAPI pipeline service.
    Initialises state and runs the full graph.

    Returns the final AgentState after all nodes complete.
    """
    initial_state: AgentState = {
        "run_id": run_id,
        "sanitized_metrics": sanitized_metrics,
        "sanitized_log_text": sanitized_log_text,
        "data_quality_findings": "",
        "log_analysis_findings": "",
        "rca_findings": "",
        "recommendations": "",
        "compliance_review": "",
        "incident_report": "",
        "audit_entries": [],
        "error": None,
    }

    final_state = graph.invoke(initial_state)
    return final_state
